cache:
  directories:
  - node_modules # cache node_module
language: node_js # set language to node_js
node_js:
  7 # use node version 7
branches:
  only: 
  - master # auto build and deploy in only master branch
script: # run after installed
- npm install # install node module
- npm run build # build project
install:
  npm install -g firebase-tools # install firebase-cli
after_success:
- firebase use --token 1/I2AvCt6OqJHEoJrUZYWrWeU0f7Vi52ytm_coYnIq7M8 # set firebase token
- firebase use --add thingtodo-56a1c # set current project
- firebase deploy --non-interactive --token "1/I2AvCt6OqJHEoJrUZYWrWeU0f7Vi52ytm_coYnIq7M8" # deploy project